column_width = 120
line_endings = "Unix"
#indent_type = "Tabs"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
syntax = "Lua52"

[sort_requires]
enabled = false
